language: python
python:
  - "3.6"
install:
  - "pip install -r requirements-test.txt"
  - "pip install pytest-cov"
  - "pip install -e ."
script: 
  - pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)